name: Branch CI
on:
  push:
    branches:
      - master
      - develop
env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  CI: true
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
          registry-url: 'https://registry.npmjs.org'
      - name: Clean install
        run: npm ci
      - name: Check eslint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test