name: Pull Request CI
on:
  pull_request:
    branches:
      - develop
env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  CI: true
  node_version: 16.15.1
jobs:
  Clean_install:
    runs-on: ubuntu-20.04
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.node_version}}
          registry-url: 'https://npm.pkg.github.com'
      - name: Cache local node modules
        uses: actions/cache@v3
        with:
          path: client_axios/node_modules
          key: ${{ runner.os }}-node_modules-${{github.sha}}
          restore-keys: ${{ runner.os }}-node_modules-${{github.sha}}
      - name: Clean install
        run: npm ci
  Check_eslint:
    runs-on: ubuntu-20.04
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    needs:
      - Clean_install
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.node_version}}
          registry-url: 'https://npm.pkg.github.com'
      - name: Cache local node modules
        uses: actions/cache@v3
        with:
          path: client_axios/node_modules
          key: ${{ runner.os }}-node_modules-${{github.sha}}
          restore-keys: ${{ runner.os }}-node_modules-${{github.sha}}
      - name: Check eslint
        run: npm run eslint
  Check_prettier:
    runs-on: ubuntu-20.04
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    needs:
      - Clean_install
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.node_version}}
          registry-url: 'https://npm.pkg.github.com'
      - name: Cache local node modules
        uses: actions/cache@v3
        with:
          path: client_axios/node_modules
          key: ${{ runner.os }}-node_modules-${{github.sha}}
          restore-keys: ${{ runner.os }}-node_modules-${{github.sha}}
      - name: Check prettier
        run: npm run prettier
  Build:
    runs-on: ubuntu-20.04
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    needs:
      - Check_eslint
      - Check_prettier
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.node_version}}
          registry-url: 'https://npm.pkg.github.com'
      - name: Cache local node modules
        uses: actions/cache@v3
        with:
          path: client_axios/node_modules
          key: ${{ runner.os }}-node_modules-${{github.sha}}
          restore-keys: ${{ runner.os }}-node_modules-${{github.sha}}
      - name: Build
        run: npm run build
  Test_and_sonar:
    runs-on: ubuntu-20.04
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    needs:
      - Build
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.node_version}}
          registry-url: 'https://npm.pkg.github.com'
      - name: Cache local node modules
        uses: actions/cache@v3
        with:
          path: client_axios/node_modules
          key: ${{ runner.os }}-node_modules-${{github.sha}}
          restore-keys: ${{ runner.os }}-node_modules-${{github.sha}}
      - name: Test
        run: npm run test:coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: -Dsonar.organization=jbwittner -Dsonar.projectKey=jbwittner_my_home_front -Dsonar.sources=. -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
